# CAPI error.py
# Translation of CAPI error values into text

WarningText = {
    "01": "Non-fatal tool error.",
    "02": "Tool does not meet unique geometry requirements.",
    "03": "Tool conficts with a previously loaded unique geometry tool.",
    "04": "Tool does not meet unique geometry requirements and conflicts with a previously loaded tool.",
    "05": "Using default marker wavelength.",
    "06": "Monitor connection issued INIT while system is in Tracking or Diagnostics mode or a tool has been loaded.",
}

ErrorText = {
    "01": "Invalid command.",
    "02": "Command too long.",
    "03": "Command too short.",
    "04": "Invalid CRC calculated for command; calculated CRC does not match the one sent.",
    "05": "Time-out on command execution.",
    "06": "Unable to set up new communication parameters.",
    "07": "Incorrect number of parameters.",
    "08": "Invalid port handle selected.",
    "09": "Invalid mode selected. ",
    "0A": "Invalid LED selected. The LED selected is out of range.",
    "0B": "Invalid LED state selected. The LED state selected is out of range.",
    "0C": "Command is invalid while in the current mode.",
    "0D": "No tool is assigned to the selected port handle.",
    "0E": "Selected port handle not initialized.",
    "0F": "Selected port handle not enabled.",
    "10": "System not initialized.",
    "11": "Unable to stop tracking.",
    "12": "Unable to start tracking.",
    "13": "Hardware error: unable to read the SROM device.",
    "14": "Invalid Position Sensor characterization parameters.",
    "15": "Unable to initialize the system.",
    "16": "Unable to start Diagnostic mode. ",
    "17": "Unable to stop Diagnostic mode.",
    "18": "Reserved",
    "19": "Unable to read device's firmware version information.",
    "1A": "Internal system error. ",
    "1B": "Reserved",
    "1C": "Unable to set marker activation signature.",
    "1D": "Unable to find SROM device IDs.",
    "1E": "Unable to read SROM device data.",
    "1F": "Unable to write SROM device data.",
    "20": "Unable to select SROM device for given port handle and SROM device ID.",
    "21": "Unable to test electrical current on tool.",
    "22": "Enabled tools are not supported by selected volume parameters.",
    "23": "Command parameter is out of range.",
    "24": "Unable to select measurement volume.",
    "25": "Unable to determine the system's supported features list.",
    "26": "Reserved",
    "27": "Reserved",
    "28": "Too many tools are enabled.",
    "29": "Reserved",
    "2A": "No memory is available for dynamic allocation (heap is full).",
    "2B": "The requested port handle has not been allocated.",
    "2C": "The requested port handle has become unoccupied.",
    "2D": "All handles have been allocated.",
    "2E": "Incompatible firmware versions.",
    "2F": "Invalid port description.",
    "30": "Requested port is already assigned a port handle.",
    "31": "Invalid input or output state.",
    "32": "Invalid operation for the device associated with the specified port handle.",
    "33": "Feature not available.",
    "34": "User parameter does not exist.",
    "35": "Invalid value type (e.g. string instead of integer).",
    "36": "User parameter value set is out of valid range.",
    "37": "User parameter array index is out of valid range.",
    "38": "User parameter size is incorrect.",
    "39": "Permission denied.",
    "3A": "Reserved",
    "3B": "File not found.",
    "3C": "Error writing to file.",
    "40": "Tool definition file error.",
    "41": "Tool characteristics not supported.",
    "42": "Device not present.",
    "E0": "API_ERROR_PD_UNINITIALIZED",
    "E1": "API_ERROR_PD_INVALID_NUM_BYTES",
    "E2": "API_ERROR_PD_INVALID_PRODUCT_FAMILY",
    "E3": "API_ERROR_PD_NOT_EXPECTING_BLOCK",
    "E4": "API_ERROR_PD_INVALID_FLASH_ADDRESS",
    "E5": "API_ERROR_PD_VERIFY_FAILED",
    "E6": "API_ERROR_PD_DATABUF_ALLOC_FAILED",
    "E7": "API_ERROR_PD_PROG_FAILED",
    "E8": "API_ERROR_PD_PACKET_SEQUENCE_ERROR",
}
